import type { FunctionalComponent } from "vue";
import {
  ArrowLeftRight,
  Banknote,
  BarChart3,
  BookOpen,
  Blocks,
  Bot,
  Boxes,
  Building2,
  CalendarClock,
  CreditCard,
  Database,
  FileSearch,
  FileText,
  Folder,
  Gauge,
  HeartPulse,
  Image,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  ListChecks,
  Lock,
  Megaphone,
  MessageSquare,
  Palette,
  PenLine,
  ReceiptText,
  Route,
  ScrollText,
  Server,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Tags,
  Ticket,
  User,
  Users,
  Wallet
} from "lucide-vue-next";

/**
 * 侧栏菜单图标注册表:菜单数据(AppShellNavItem.icon)用 kebab-case 字符串引用,
 * 在这里集中映射到 lucide 组件,新增菜单图标时在此登记。
 */
const sidebarIcons: Record<string, FunctionalComponent> = {
  "arrow-left-right": ArrowLeftRight,
  banknote: Banknote,
  "bar-chart-3": BarChart3,
  "book-open": BookOpen,
  blocks: Blocks,
  bot: Bot,
  boxes: Boxes,
  "building-2": Building2,
  "calendar-clock": CalendarClock,
  "credit-card": CreditCard,
  database: Database,
  "file-search": FileSearch,
  "file-text": FileText,
  folder: Folder,
  gauge: Gauge,
  "heart-pulse": HeartPulse,
  image: Image,
  "key-round": KeyRound,
  landmark: Landmark,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  lock: Lock,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  palette: Palette,
  "pen-line": PenLine,
  "receipt-text": ReceiptText,
  route: Route,
  "scroll-text": ScrollText,
  server: Server,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  "sliders-horizontal": SlidersHorizontal,
  tags: Tags,
  ticket: Ticket,
  user: User,
  users: Users,
  wallet: Wallet
};

export function resolveSidebarIcon(name?: string): FunctionalComponent | undefined {
  return name ? sidebarIcons[name] : undefined;
}
